### ISSUE TITLE
RHSUSF IHADSS helmet not equipping when NVGs are added from common gear

### ISSUE THREAD

**Issue by Leubzo** [PXG-Arma/Scripts#36]
IHADSS helmet equips fine when no NVGs are added from common gear.sqf, but doesn't get equipped when using the faction's own gear or uniforms sqf even after removing NVGs from there using unlinkItem

**Comment by SewerynRoznowski** [comment]
This is due to the IHADSS helmet taking up both NVG and Helmet slot. 
The order in which the scirpt is executed is Uniforms > Common Gear > Faction Gear. 
Common gear will overwrite the helmet and remove it, same with faction gear. 

This should be easily fixed by adding the IHADSS via Faction gear.

**Comment by SewerynRoznowski** [comment]
Adding via faction's gear.sqf works.

**Comment by Leubzo** [comment]
Since we only use one pilot loadout for all types of rotary and fixed wing assets, it's better to keep the IHADSS in the AH-64 inventory only, so that pilots can switch between it and regular helmet + NVGs in case they switch air asset.

**Comment by Real-ADK** [comment]
closed
