### ISSUE TITLE
Motorpool: First vehicle spawned has wrong cargo space amount (inconsistent behavior)

### ISSUE THREAD

**Issue by DrJaffas22** [PXG-Arma/Scripts#60]
Seen it 2 times now where the first vic spawned by a faction has more cargo slots (auto fixes itself for second vic)

**Comment by Conorrob** [comment]
Unable to replicate in both missions where this has occurred. Need more instances.

**Comment by DrJaffas22** [comment]
Lorts OP 
OP Clarity with the M1083a1p2-b

**Comment by DragonHunter003** [comment]
I've seen it happen myself a couple of times as well. As far as I can tell it's due to the script that changes cargo size sometimes running before the vehicle is fully initialized server side therefor the server overrides the cargo values with the default ones again. Not sure if that can be fixed other than delaying the script for a bit. (Which imo should be avoided as much as possible)
